export { default as userRouter } from "./user.route";
export { default as categoryRouter } from "./category.route";
export { default as uploadRouter } from "./upload.route";
export { default as blogRouter } from "./blog.route";
export { default as likeRouter } from "./like.route";
export { default as notificationRouter } from "./notification.route";
export { default as commentRouter } from "./comment.route";
export { default as statsRouter } from "./stats.route";
export { default as aiRouter } from "./ai.route";
